#!/bin/bash

echo """See GitHub page for documentation: https://github.com/UPPMAX/uppmax_in_a_can

-----------------------------------------
For the impatient:
# run this first time using it
$ singularity exec $SINGULARITY_NAME uppmax_init

# start the container
$ ./start_node.sh $SINGULARITY_NAME
-----------------------------------------
     _   _ ____  ____  __  __    _    __  __ 
    | | | |  _ \|  _ \|  \/  |  / \   \ \/ / 
    | | | | |_) | |_) | |\/| | / _ \   \  /  
    | |_| |  __/|  __/| |  | |/ ___ \  /  \  
     \___/|_|   |_|   |_|  |_/_/   \_\/_/\_\ 
  ___ _   _         _          ____    _    _   _  
 |_ _| \ | |       / \        / ___|  / \  | \ | | 
  | ||  \| |_____ / _ \ _____| |     / _ \ |  \| | 
  | || |\  |_____/ ___ \_____| |___ / ___ \| |\  | 
 |___|_| \_|    /_/   \_\     \____/_/   \_\_| \_| 



Hello, and welcome to UPPMAX-in-a-can

In short, you have to have have sshfs working with the option user_allow_other enabled in your fuse.conf. To see more info about this, run

singularity exec $SINGULARITY_NAME sshfs_help


If you have just downloaded the container file you will have to run a initialization command and the container will create a couple of files for you, in the directory you are standing when executing the command:

singularity exec $SINGULARITY_NAME uppmax_init


This command should have created a folder called mnt/ and a file named unmount_sshfs.sh

To start using the container just run the following command:

./start_node.sh $SINGULARITY_NAME


and it will use sshfs (must be in your PATH) to mount the sw, proj, crex and home folder on UPPMAX, to the folders inside mnt/. It will then start the container automatically. If you have already mounted the folders in a previous run of the command it will skip re-mounting them and just start the container.

If you want to unmount the sshfs mounts, just run 

./unmount_sshfs.sh

"""
