#!/bin/bash

set -e

# copy the mounting files to where the user is
cp -v /uppmax_init/*.sh .

# print success message
echo """ 
To start, run:

./start_node.sh $SINGULARITY_NAME

To start the container manually you can also run

singularity shell --containall --bind mnt/crex:/crex,mnt/etc:/etc,mnt/home/:/home/,mnt/proj:/proj,mnt/sw:/sw,mnt/usr/local/Modules:/usr/local/Modules $SINGULARITY_NAME

"""
